version: '3.3'

services: 
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
        ports: 
            - "9200:9200"
            - "9300:9300"
        networks: 
            - app-network 
    api:
        build: "."
        depends_on: 
            - elasticsearch
        ports:
            - "5000"
        environment:
            ELASTICSEARCHHOST: elasticsearch:9200
        restart: "always"
        networks: 
            - app-network
        deploy:
            replicas: 5
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - api
        ports: 
            - "80:80"
        networks: 
            - app-network

#Docker Networks
networks: 
    app-network:
        driver: bridge